services:
  java_app:
    container_name: java_app
    image: minhductran042/java_app:1.0.0
    build: .
    ports:
      - "8081:8081"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://java_db:5432/test_db
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
      JWT_SECRET_KEY: 6X48eG6MIx3ynHl3f5YYXNwhU7IMU22IKxb48T1nW3s=
      JWT_EXPIRATION_TIME: 3600000
    env_file:
      - .env
    volumes:
      # Mount logs directory để lưu trữ logs bên ngoài container
      - ./logs:/app/logs
      # Mount config directory để có thể thay đổi config mà không rebuild
      - ./config:/app/config:ro
    restart: unless-stopped
    depends_on:
      - java_db

  java_db:
    container_name: java_db
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: test_db
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./db/init:/docker-entrypoint-initdb.d:ro
      - ./db/backup:/backup


volumes:
  pgdata: {}