server:
  port: 8082
spring:
  config:
    activate:
      on-profile: prod
  logging:
    file:
      name: logs/application-test.log
    level:
      root: WARN
openapi:
  service:
    api-docs: api-services
    service: http://localhost:${server_port}
    title: API Services
    version: 1.0.0