server:
  port: 8084
spring:
  config:
    activate:
      on-profile: dev
  datasource:
    url: jdbc:postgresql://localhost:5432/test_db
    username: postgres
    password: postgres
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true

# Cấu hình logging cho DEV environment
logging:
  file:
    name: logs/application-dev.log
  level:
    root: INFO
    com.minhductran.tutorial: DEBUG  # Package của bạn với level DEBUG để debug
    org.springframework: INFO
    org.hibernate: DEBUG            # Chi tiết SQL queries
    org.springframework.security: DEBUG  # Chi tiết về security
    org.springframework.web: DEBUG      # Chi tiết về web requests
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level [DEV] %logger{36} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level [DEV] %logger{36} - %msg%n"

openapi:
  service:
    api-docs: api-services
    service: http://localhost:${server_port}
    title: API Services
    version: 1.0.0

security:
  jwt:
    secret-key: 6X48eG6MIx3ynHl3f5YYXNwhU7IMU22IKxb48T1nW3s=
    expiration-time: 3600000
