server:
  port: 8081
spring:
  config:
    activate:
      on-profile: test
  logging:
    file:
      name: logs/application-prod.log
    level:
      root: ERROR
      com.example: WARN  # Giả sử package ứng dụng của bạn là com.example
openapi:
  service:
    api-docs: api-services
    service: http://localhost:${server_port}
    title: API Services
    version: 1.0.0