spring:
  application:
    name: SpringTutorial
  profiles:
    active: dev
  logging:
    file:
      name: logs/application.log
    level:
      root: INFO #TRACE->DEBUG->INFO->WARN->ERROR

project:
  logo: logo/